// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function CreateInvoice(arg1:repository.InvoiceInput):Promise<repository.InvoiceDetail>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeleteVendor(arg1:number):Promise<void>;

export function EmailInvoice(arg1:repository.EmailInvoiceInput):Promise<void>;

export function ExportInvoicePDF(arg1:number):Promise<string>;

export function GetDashboard():Promise<repository.DashboardSummary>;

export function GetInvoice(arg1:number):Promise<repository.InvoiceDetail>;

export function GetSettings():Promise<repository.AppSettings>;

export function ListCustomerLookup(arg1:string,arg2:string):Promise<Array<repository.CustomerLookup>>;

export function ListCustomers(arg1:string):Promise<Array<repository.Customer>>;

export function ListInvoices(arg1:string):Promise<Array<repository.InvoiceListItem>>;

export function ListVendors(arg1:string):Promise<Array<repository.Vendor>>;

export function Login(arg1:string,arg2:string):Promise<repository.AuthSession>;

export function SaveCustomer(arg1:repository.CustomerInput):Promise<repository.Customer>;

export function SaveSettings(arg1:repository.AppSettings):Promise<repository.AppSettings>;

export function SaveVendor(arg1:repository.VendorInput):Promise<repository.Vendor>;

export function SelectBusinessLogo():Promise<string>;
