// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteVendor(arg1) {
  return window['go']['main']['App']['DeleteVendor'](arg1);
}

export function EmailInvoice(arg1) {
  return window['go']['main']['App']['EmailInvoice'](arg1);
}

export function ExportInvoicePDF(arg1) {
  return window['go']['main']['App']['ExportInvoicePDF'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetInvoice(arg1) {
  return window['go']['main']['App']['GetInvoice'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListCustomerLookup(arg1, arg2) {
  return window['go']['main']['App']['ListCustomerLookup'](arg1, arg2);
}

export function ListCustomers(arg1) {
  return window['go']['main']['App']['ListCustomers'](arg1);
}

export function ListInvoices(arg1) {
  return window['go']['main']['App']['ListInvoices'](arg1);
}

export function ListVendors(arg1) {
  return window['go']['main']['App']['ListVendors'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function SaveCustomer(arg1) {
  return window['go']['main']['App']['SaveCustomer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveVendor(arg1) {
  return window['go']['main']['App']['SaveVendor'](arg1);
}

export function SelectBusinessLogo() {
  return window['go']['main']['App']['SelectBusinessLogo']();
}
